openapi: 3.0.1
info:
    title: Coinbase API
    description: The Coinbase v2 API (converted from Swagger to OpenAPI by kanekoshoyu)
    contact:
        name: CoinFabrik
        url: http://www.coinfabrik.com/
    version: 2.0.0
servers:
    - url: https://api.coinbase.com/v2
security:
    - coinbaseAccessCode: []
paths:
    /users/{user_id}:
        get:
            tags:
                - Users
            summary: Show a user
            description: Get any user’s public information with their ID.
            security:
                - coinbaseAccessCode: []
    /user:
        get:
            tags:
                - Users
            summary: Show current user
            description: >-
                Get current user’s public information. To get user’s email or private
                information, use permissions wallet:user:email and wallet:user:read.
            security:
                - coinbaseAccessCode: []
        put:
            tags:
                - Users
            summary: Update current user
            description: Modify current user and their preferences.
            security:
                - coinbaseAccessCode:
                      - wallet:user:update
    /user/auth:
        get:
            tags:
                - Users
            summary: Show authorization information
            description: >-
                Get current user’s authorization information including granted scopes
                and send limits when using OAuth2 authentication.
            security:
                - coinbaseAccessCode: []
    /accounts:
        get:
            tags:
                - Accounts
            summary: List accounts
            description: >-
                Lists current user’s accounts to which the authentication method has
                access to.
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:read
        post:
            tags:
                - Accounts
            summary: Create account
            description: Creates a new account for user.
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:create
    /accounts/{account_id}:
        get:
            tags:
                - Accounts
            summary: Show an account
            description: >-
                Show current user’s account. To access user’s primary account, primary
                keyword can be used instead of the account id in the URL.
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:read
        put:
            tags:
                - Accounts
            summary: Update account
            description: Modifies user’s account name.
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:update
        delete:
            tags:
                - Accounts
            summary: Delete account
            description: |
                Removes user’s account. In order to remove an account it can’t be

                - Primary account
                - Account with non-zero balance
                - Fiat account
                - Vault with a pending withdrawal
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:delete
    /accounts/{account_id}/primary:
        get:
            tags:
                - Accounts
            summary: Set account as primary
            description: Promote an account as primary account.
            security:
                - coinbaseAccessCode:
                      - wallet:accounts:update
    /accounts/{account_id}/addresses:
        get:
            tags:
                - Addresses
            summary: List addresses
            description: |
                Lists addresses for an account.

                *Important*: Addresses should be considered one time use only.
            security:
                - coinbaseAccessCode:
                      - wallet:addresses:read
        post:
            tags:
                - Addresses
            summary: Create address
            description: >
                Creates a new address for an account. As all the arguments are optinal,
                it’s possible just to do a empty POST which will create a new address.
                This is handy if you need to create new receive addresses for an account
                on-demand.

                Addresses can be created for all account types. With fiat accounts,
                funds will be received with Instant Exchange.
            security:
                - coinbaseAccessCode:
                      - wallet:addresses:create
    /accounts/{account_id}/addresses/{address_id}:
        get:
            tags:
                - Addresses
            summary: Show an address
            description: >
                Show an individual address for an account.

                Regular bitcoin address can be used in place of address_id but the
                address has to be associated to the correct account.
                  
                *Important* Addresses should be considered one time use only.
            security:
                - coinbaseAccessCode:
                      - wallet:addresses:read
    /accounts/{account_id}/addresses/{address_id}/transactions:
        get:
            tags:
                - Addresses
            summary: List address’s transactions
            description: >
                list transactions that have been sent to a specific address. Regular
                bitcoin address can be used in place of address_id but the address has
                to be associated to the correct account.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:read
    /accounts/{account_id}/transactions:
        get:
            tags:
                - Transactions
            summary: List transactions
            description: >-
                Lists account’s transactions. See Transaction resource for more
                information.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:read
        post:
            tags:
                - Transactions
            summary: Send or request money
            description: >
                Type=send

                =========


                Send funds to a bitcoin address or email address. No transaction fees
                are required for off blockchain transactions, and Coinbase waives fees
                for on-blockchain transactions greater than 0.0001 BTC, up to a
                threshold of 25 per day. Read more about free transactions.


                When used with OAuth2 authentication, this endpoint requires two factor
                authentication unless used with wallet:transactions:send:bypass-2fa
                scope.


                If the user is able to buy bitcoin, they can send funds from their fiat
                account using instant exchange feature. Buy fees will be included in the
                created transaction and the recipient will receive the user defined
                amount.


                To create a multisig transaction, visit Multisig documentation.


                Type=request

                ============


                Requests money from an email address.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:send
                      - wallet:transactions:request
    /accounts/{account_id}/transactions/{transaction_id}:
        get:
            tags:
                - Transactions
            summary: Show a transaction
            description: >-
                Show an individual transaction for an account. See Transaction resource
                for more information.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:read
        delete:
            tags:
                - Transactions
            summary: Cancel request money
            description: >-
                Lets a user cancel a money request. Money requests can be canceled by
                the sender or the recipient.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:request
    /accounts/{account_id}/transactions/{transaction_id}/complete:
        post:
            tags:
                - Transactions
            summary: Complete request money
            description: >-
                Lets the recipient of a money request complete the request by sending
                money to the user who requested the money. This can only be completed by
                the user to whom the request was made, not the user who sent the
                request.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:request
    /accounts/{account_id}/transactions/{transaction_id}/resend:
        post:
            tags:
                - Transactions
            summary: Re-send request money
            description: >-
                Lets the user resend a money request. This will notify recipient with a
                new email.
            security:
                - coinbaseAccessCode:
                      - wallet:transactions:request
components:
    securitySchemes:
        coinbaseAccessCode:
            type: oauth2
            flows:
                authorizationCode:
                    authorizationUrl: https://www.coinbase.com/oauth/authorize
                    tokenUrl: http://www.coinbase.com/oauth/token
                    scopes:
                        wallet:accounts:read: List user’s accounts and their balances
                        wallet:accounts:update: Update account (e.g. change name)
                        wallet:accounts:create: Create a new account (e.g. BTC wallet)
                        wallet:accounts:delete: Delete existing account
                        wallet:addresses:read: List account’s bitcoin addresses
                        wallet:addresses:create: Create new bitcoin addresses for wallets
                        wallet:buys:read: List account’s buys
                        wallet:buys:create: Buy bitcoin
                        wallet:checkouts:read: List user’s merchant checkouts
                        wallet:checkouts:create: Create a new merchant checkout
                        wallet:deposits:read: List account’s deposits
                        wallet:deposits:create: Create a new deposit
                        wallet:notifications:read: List user’s notifications
                        wallet:orders:read: List user’s merchant order
                        wallet:orders:create: Create a new merchant order
                        wallet:orders:refund: Refund a merchant order
                        wallet:payment-methods:read: List user’s payment methods (e.g. bank accounts)
                        wallet:payment-methods:delete: Remove existing payment methods
                        wallet:payment-methods:limits: >-
                            Get detailed limits for payment methods (useful for performing
                            buys and sells). This permission is to be used together with
                            wallet:payment-methods:read
                        wallet:sells:read: List account’s sells
                        wallet:sells:create: Sell bitcoin
                        wallet:transactions:read: List account’s transactions
                        wallet:transactions:send: Send bitcoin
                        wallet:transactions:request: Request bitcoin from a Coinbase user
                        wallet:transactions:transfer: Transfer funds between user’s two bitcoin accounts
                        wallet:user:read: >-
                            List detailed user information (public information is available
                            without this permission)
                        wallet:user:update: Update current user
                        wallet:user:email: Read current user’s email address
                        wallet:withdrawals:read: List account’s withdrawals
                        wallet:withdrawals:create: Create a new withdrawal
x-original-swagger-version: "2.0"
